'use client';
import {useState,useEffect,useRef,type ReactNode} from 'react';
export const definitions:Record<string,{title:string,text:string}>={
  agl:{title:'Adjusted Games Lost (AGL)',text:'Football Outsiders / FTN’s estimate of injury-related availability lost by expected starters and important contributors during the regular season. Missed games add to the total; playing while listed as injured can add a fraction. It is not a count of diagnoses, and a star is not weighted more than another starter.'},
  index:{title:'Injury index',text:'A comparison scale: 100 is that season’s NFL average. A team at 140 has 40% more AGL than the league average; a team at 50 has half as much. Higher means more injury burden. It is not an individual player’s chance of getting hurt.'},
  workload:{title:'Playing time in earlier games',text:'The model uses a player’s total snaps and offensive/defensive snap share in the last earlier game, plus snaps and games in the previous 28 days. All workload comes strictly before the game leading to the next report. Example: predicting a report before Week 8, with Week 7 as the current game, uses snap history before Week 7. Week 7 could already have been shortened by an injury. This does not measure first-half versus second-half workload, practices, collisions or prior-year fatigue.'},
  history:{title:'Earlier injury reports',text:'How often a player appeared on public physical-injury or condition reports in the preceding 28 and 365 days, plus time since the last report. Several weekly listings may all refer to one lingering injury; this is report history, not a tally of separate injuries.'},
  playerSnaps:{title:'Player-snaps',text:'Participation summed across players. An ordinary offensive play with 11 players contributes about 11 offensive player-snaps. The team totals here add offensive and defensive participation. They do not measure distance run, collision force, practice work or actual fatigue.'},
  interval:{title:'The uncertainty range',text:'A 95% confidence interval describes uncertainty in an estimated average or association under the model’s assumptions. It is not the range containing 95% of individual teams. When an estimated effect’s interval includes zero, these data do not clearly distinguish it from no association; a wide interval can still allow meaningful harm.'},
  cluster:{title:'Team profiles (clusters)',text:'Groups of team-seasons with similar age, continuity, playing-time concentration, volume, playoff history and rushing share. Injury outcomes were not used to form them. Their boundaries overlap, so they are descriptive summaries rather than distinct medical risk categories.'},
  age:{title:'Age weighted by playing time',text:'The average age of the players who actually played, with more influence given to those who took more offensive or defensive snaps. Age is measured on September 1 of the earlier season. It does not describe every player on the next season’s opening roster.'},
  continuity:{title:'Historical roster continuity',text:'The share of an earlier season’s snaps taken by players who also played for that club the year before. For the 2024 profile, SF’s 82.5% means 2023 snaps by players who also played for SF in 2022. It does not measure how many of those players returned for 2024.'},
  concentration:{title:'Concentration of playing time',text:'The share of a team’s offensive and defensive player-snaps taken by its 22 most-used players. A higher number means the core handled more of the work. It is not an overuse threshold; good health itself can allow a stable core to play more.'},
  runShare:{title:'Rushing share',text:'Carries divided by carries plus pass attempts plus sacks. It includes quarterback scrambles and kneel-downs, and reflects score and game situation. It is not a pure measure of designed runs or coaching philosophy.'},
  importance:{title:'Predictive importance',text:'We shuffle one group of inputs and see how much the model’s predictions worsen on data it did not train on. A larger drop means that information helped this model more. It does not say what caused an injury, or what percentage of injuries a factor explains.'},
  precision:{title:'Average precision (AP)',text:'A 0-to-1 score for how well a model brings positive cases toward the top of its predictions. Larger is better. Chart values show the change multiplied by 100: a loss of 2.8 AP percentage points means the AP score fell by 0.028. This is not a change in injury probability.'},
  mix:{title:'Share of injury reports',text:'The proportion of public physical-injury/condition listings assigned to a body region. If a listing names two different regions, each gets half a unit. One persistent injury can appear in many weeks. Players sent directly to injured reserve may be missing entirely.'},
  episode:{title:'A new reporting episode',text:'A player’s first observed listing for a body region, or a listing at least 28 days after the previous report in that region. This helps reduce repeated weekly listings, but it does not establish a new medical injury or confirmed recovery.'},
  timed:{title:'Timed injury announcements',text:'The first play-by-play announcement per player per game explicitly stating that he was injured during the play, assigned to the quarter of that play. Return-to-game updates are excluded. This captures visible game announcements, not every injury or the full medical record.'}
};
export function Metric({term,children}:{term:string;children?:ReactNode}){const[open,setOpen]=useState(false);const ref=useRef<HTMLSpanElement>(null);const d=definitions[term];useEffect(()=>{if(!open)return;function close(e:MouseEvent){if(!ref.current?.contains(e.target as Node))setOpen(false)}function key(e:KeyboardEvent){if(e.key==='Escape')setOpen(false)}document.addEventListener('click',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',key)}},[open]);if(!d)return <>{children}</>;return <span ref={ref} className="sports-term"><button type="button" className="sports-term-trigger" aria-expanded={open} onClick={()=>setOpen(!open)}>{children||d.title}<span aria-hidden="true" className="sports-term-mark">ⓘ</span></button>{open&&<span className="sports-term-definition" role="note"><strong>{d.title}</strong><span>{d.text}</span><button type="button" aria-label={`Close definition of ${d.title}`} onClick={()=>setOpen(false)}>Close ×</button></span>}</span>}
export function Glossary(){return <dl className="sports-glossary">{Object.entries(definitions).map(([key,d])=><div key={key}><dt>{d.title}</dt><dd>{d.text}</dd></div>)}</dl>}
